### ISSUE TITLE
Dokumentation neue Elemente fm-library plugin 

### ISSUE THREAD

**Issue by davidbortenreuter** [fm-online/fm-library#3]
Es soll eine Anleitung  entstehen, wie man im fm-library plugin neue Elemente anlegt bzw. Änderungen vornimmt und die dann in den DA importiert.

**Comment by schafschur** [comment]
Link zu der Doku: https://github.com/fm-online/fm-doku/blob/master/1.Uebergreifendes/Frontend/FM-Library-Guide.md
